### ISSUE TITLE
Migrate Sandy from 0.18 to 0.22, as  Jones did

### ISSUE THREAD

**Issue by jpskenn** [jpskenn/qmk_firmware#2]
#### 対応方針

JonesがQMKへマージされて以降におこなわれたアップデート、つまりjpskenn以外のメンテナー等によりおこなわれたアップデートを、Sandyへ適用する。

Jonesのv1に対するアップデートを元とする。

Sandyは開発経緯により`dn0020`, `dn0030`, `v01`の3バージョンのファームウェアが存在するが、それらすべてに適用する。

#### 注意点

自宅とリモート環境からの適用作業となるが、リモート環境にはビルド環境がないため、ビルド結果を見ずにコミットする。

それらコミットは、自宅においてビルド結果を確認する。

#### アップデート: 対応済み

- [x] Move RGBLight animations to data driven (qmk#21635)

    RGBアニメをinfo.json化。
    dn0030のみ。

- [x] jones/v1: fix layout offset and disable audio on via keymap (qmk#21468)

    レイアウトオフセット修正  
    →Jonesのみ。対応不要

- [x] Fix encoder map declarations (qmk#21435)

  エンコーダーマッピングの方向指定  
  →マジックナンバーから定数へ変更

    ```diff
    + const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][2] = {
    - const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
    ```

- [x] Move miscellaneous defines to data driven (qmk#21382)

    コメント内の古い定義は、コメントごと消す。

    ```c++
    /* COL2ROW, ROW2COL*/
    // No need to define DIODE_DIRECTION for Jones' custom Round-Robin matrix.
    //#define DIODE_DIRECTION COL2ROW
    ```

    SandyはCOL2ROWを使っていてinfo.json化するので、これは対象外。

- [x] Move RGBLIGHT_HUE/SAT/VAL_STEP to data driven (qmk#21292)

    RGBLIGHT_HUEとかをinfo.jsonへ。  
    VALはデフォルト値のため、喜寿せず。

- [x] Remove encoder in-matrix workaround code (qmk#20389)

    エンコーダーの仮想マッピングを廃止

  - config.h
    エンコーダからマトリクスの仮想定義を削除

  - info.json
    エンコーダからマトリクスの仮想定義を削除

  - keyboard.c
    エンコーダーへ割り当てた処理を削除
    - keymap.cでキーコードの仮想割り当てやめる

    -　キーマップ/rules.mk

    ```diff
    + ENCODER_MAP_ENABLE = yes
    ```

    - キーマップ/keymap.c
    仮想定義に割り当ててきたキーコードを削除
    encoder_mapに、エンコーダーで動作させたいキーコードを割り当て（**注意：キーマップレベルでの定義**）

    - VIA定義ファイル（QMK外）
    QMKには直接関係しないが、VIAとRemapがEncoder mapに対応したため、VIA V3向けの定義ファイルも作成した。  
    Sandyプロジェクトにファイルを追加。

- [x] Move RGBLED_NUM to data driven (qmk#21278)

    →info.json化

- [x] Move RGBLIGHT_SLEEP to data driven (qmk#21072)

    ```diff
    - // #define RGBLIGHT_SLEEP  /* If defined, the RGB lighting will be switched off when the host goes to sleep */
    ```

    Sandy未使用だが、rules.mkの関連記述を削除した。

- [x] Move RGBLIGHT_LED_MAP to data driven (qmk#21095)

    LEDマッピングしてるときのみ。
    Sandy未使用。

- [x] Move RGBLIGHT_LIMIT_VAL to data driven (qmk#20974)

    info.json化の対象だが、defaultが255なので、あえて記述する必要なし。

- [x] Remove use of layout macros for music_map (qmk#20634)

    →musicでmusic_map使用の場合のみ。対応不要

- [x] Move single LAYOUTs to data driven (qmk#20365)

    →info.jsonでマトリックス指定
    →v1.cでv1.hをincludeせず、QMK_KEYBOARD_Hをインクルード

    ```diff
    - #include "v1.h"
    + #include QMK_KEYBOARD_H
    ```

    →v1.h削除（レイアウト部分）

- [x] Migrate rgblight.pin and RGB_DI_PIN to ws2812.pin (qmk#20303)

    config.hで　`RGB_DI_PIN` -> `WS2812_DI_PIN`

    -> info.jsonへ

    ```diff
    + "ws2812": {
    +   "pin": "B7"
    + },
    ```

- [x] [Core] Refactor keyevent_t for 1ms timing resolution (qmk#15847)

    →キーイベントのタイマー指定方法変更

    ```diff
        keyevent_t encoder_event = (keyevent_t) {
            .key = encoder_state[index] >> 1 ? encoder_cw[index] : encoder_ccw[index],
            .pressed = false,
    -       .time = (timer_read() | 1)
    +       .time = timer_read(),
    +       .type = KEY_EVENT
    ```

- [x] Remove RGB_DI_PIN ifdefs (qmk#20218)

    →RGB_DI_PINについての#ifdefをやめる

    ```diff
    - #ifdef RGB_DI_PIN
    -
    - hogehoge
    -
    - #endif
    ```

- [x] Remove more empty headers (qmk#20155)

    keyboard.hを#includeするだけのkeyboard.cを消す  
    →Sandyはエンコーダーのマッピングに関する処理が書いてあるので、対象外。

- [x] Fix layout macro keys with no matrix position (qmk#20033)

    マトリクス定義をミスってるところの修正。  
    →Sandyは大丈夫っぽい

- [x] Move matrix config to info.json, part 1 (qmk#19985)

    →マトリックスピン（MATRIX_ROW_PINSとか）をinfo.json化

- [x] Move encoder config to data driven (qmk#19923)

    →エンコーダー指定をinfo.json化

- [x] Remove matrix size defines (qmk#19581)

    →マトリックスサイズ（MATRIX_ROWSとCOLS）の記述を削除
    →info.jsonにも記述はないが、普通にビルドOK

- [x] Move Bootmagic config to data driven (qmk#19860)

    →Bootmagic指定をinfo.json化  
    →Sandyは使ってないはず？

- [x] Remove unused RGBLight defines from config.h (qmk#19859)

    未使用の定義（コメントアウトしてあるもの）があれば消す。

- [x] Migrate MCU and BOOTLOADER to data-driven (qmk#19529)

    →MCUまわりをinfo.json化

    info.json

    ```diff
    +   "processor": "atmega32u4",
    +   "bootloader": "atmel-dfu",
    ```

    rules.mk

    ```diff
    -   # MCU name
    -   MCU = atmega32u4
    -
    -   # Bootloader selection
    -   BOOTLOADER = atmel-dfu
    ```

- [x] Remove unused SOFT_SERIAL_PIN from config.h (qmk#19768)

    →Sandy未使用

- [x] Remove unused Bootmagic row/col defines from config.h (qmk#19761)

    →Sandy未使用

- [x] Remove unused GRAVE_ESC_CTRL_OVERRIDE from config.h (qmk#19752)

    →Sandy未使用

- [x] Remove IS_HOST_LED_ON and migrate usages (qmk#19753)

    →ホストのLED状態読み取りを変更。  

    ```diff
    -    if (IS_HOST_LED_ON(USB_LED_CAPS_LOCK)) {
    +    if (host_keyboard_led_state().caps_lock) {
    ```

- [x] Remove unused LOCKING_SUPPORT_ENABLE from config.h (qmk#19748)

    →Sandy未使用

- [x] Debounce defines cleanup (qmk#19742)

    →debounceの設定は消す

    ```diff
    - /* Debounce reduces chatter (unintended double-presses) - set 0 if debouncing is not needed */
    - #define DEBOUNCE 5
    ```

    →25keysさんのチャタリング防止ネタは、コメントアウトで書いてるだけなので、実害はない。
    →が、どうせ使ってないので消す。

- [x] Remove usages of config_common.h from config.h files. (qmk#19714)

    →#include "config_common.h"削除

    作業メモ

    ```text
    develop_Sandyへ、2件コミットしてしまっていた分は、家にてRevertをかけた。

    topic_sandy_qmk_v22_migrationブランチに切り替えて、最初（一番下）から作業やりなおし
    ```

- [x] Update use of legacy keycodes (qmk#19120)

    古いキーコードを更新（音楽系）  
    →Sandy対応不要

- [x] Remove legacy keycodes, part 5 (qmk#18710)

    →`KC_SLCK` -> `KC_SCRL`

- [x] Remove legacy international keycodes (qmk#18588)

    →`LANG1` -> `LNG1`, `LANG2` -> `LNG2`

- [x] Move keyboard USB IDs and strings to data driven: J (qmk#17837)

    →USB関連をinfo.json化。  

- [x] Rename keymap_extras headers for consistency (qmk#16939)

    →日本語キーマップのヘッダファイル名変更

    ```diff
    -   #include "keymap_jp.h"
    +   #include "keymap_japanese.h"
    ```

    →Sandyは変更済みの`keymap_japanese.h`を使用済み。

- [x] Remove NO_ACTION_MACRO and NO_ACTION_FUNCTION from keyboard config.h

    →定義削除

    ```diff
    -   #define NO_ACTION_MACRO
    -   #define NO_ACTION_FUNCTION
    ```

    →Sandyに該当箇所なし。

- [x] [keyboard]Add v1 to jones keyboard (qmk#14405)

    ここからはじまり

#### その他の確認事項

- [x] Bootmagic関連

    `rules.mk`に以下の記述があるが、残しておいてもよいのか？  
    削除必要？

    ```Makefile
    BOOTMAGIC_ENABLE = no       # Virtual DIP switch configuration
    ```

    →info.jsonではbootmagic, enabledのデフォルトがfalseなので、消してOK。

- [x] Sandy固有機能

    ダイナミックマクロの引数が変更になって、ビルドでエラー。
    →引数変更に対応。
